[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor --chip esp32s3"

[env]
ESP_LOG="info"
# PhotoPainter has 8MB octal PSRAM (ESP32-S3-WROOM-1-N16R8)
ESP_HAL_CONFIG_PSRAM_MODE="octal"
# Custom partition table for flash cache
ESP_BOOTLOADER_PARTITION_TABLE="partitions.csv"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["alloc", "core"]
